name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  schedule:
    - cron: '*/5 * * * *'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.3']
    name: integration-tests (PHP ${{ matrix.php-versions }})
    steps:
      - uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-progress
      - name: Run test suite
        run: |
          vendor/bin/phpunit --color tests/
        env:
          OCI_REGION: us-ashburn-1
          OCI_USER_ID: ocid1.user.oc1..aaaaaaaafurtlu5qdtupk3kwrjika6gjjbtcp7qnmw2nxvjeyf7mpzxa22zq
          OCI_TENANCY_ID: ocid1.tenancy.oc1..aaaaaaaa34x6qespw6rqsrk5powtt4idagqaipkxmz47xq3gfzukmjmutc6q
          OCI_KEY_FINGERPRINT: b1:64:fd:7d:34:05:09:12:b2:74:d7:bd:19:39:64:14
          OCI_PRIVATE_KEY_FILENAME: https://objectstorage.us-ashburn-1.oraclecloud.com/p/XwIlaYtlzcO7l2Knhqtsc3IT0ds2NPR1Jhndv5m4dQ7Co8u_uhJtm055nE7To00h/n/id3hebii3dnh/b/github-keys/o/paulr315@gmail.com-2026-05-18T18_29_48.816Z.pem
          OCI_SUBNET_ID: ocid1.subnet.oc1.iad.aaaaaaaa4jmbxm4hhvkymhm6w3ihbyb6au6qvedvrfvnubjj2d7lfvxy72qa
          OCI_IMAGE_ID: ocid1.image.oc1.iad.aaaaaaaab2x4nv7xedry7suxpx35qguxn5pffu2eom7sw2eb4e5qsw7v72wa
          OCI_OCPUS: 4
          OCI_MEMORY_IN_GBS: 24
          OCI_SHAPE: VM.Standard.A1.Flex
          OCI_SSH_PUBLIC_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCgl5zh1VmgyS27CrgIUTcc6yvM9YBmYVR5Yt41OvkD2eP5TBV1PI5hnR0h3joiAsRwPMB6e8my22tlrH7MfYDrK0NmEfnjfKtKkKjkuxIq4oWxINo1myhykNKBc9ce9M+gc5+ZbqRbJENclknGCUQ2VPHfYynIZ5KdtrPOb3QOkKt3i97O7c5cOxaPwp0vhlryIHmbuaHtRrh2YR8X5j1zrbhyVWPAUmica704JF+wGcgQAaaKhi37swkhlxN7ozbl1nJjCZlGbSV9KrXRxYUUt6KNBTatzSylatPqqHcElc0+DBUkX2Sh/Jdgxbw4gCDHA7P0i1rg+g464cs4/aJMKJxEzs/ZwEi3AleYAYFw1L6eSvCqpkFuOVkYir1Hqn5tU/bQoz/XDIpIq1HCT03Vemdoo4HD/bIWPYYCMVsfheJB4X5VO3KLknlbjvMZqg2MG+gAo5/hFxMkspJTVNQHTDz9gtbPi5lVzoRGjSmQR23Aqya8UdzClZUXqMNLVe59AXYjWZ3ASboAxQgzDk9kusLbQGjMn70G+ErYOPDI66zAj1x2GAk74ec4nEwQEL2FHA/K1IvARZ94xDvC4VGcAjUkaPYwNt6hVJ7TrEwTPGac8NZYqMUyxM1f0Isamb96ZhzKMFNrSE99fTUP2KvfSXFra0N3N5dH6P7OfWNe9w== tsb\prossi24@TSB-LT42
